### ISSUE TITLE
Broken Site when trying to self qualify on WPN-05

### ISSUE THREAD

**Issue by nevara** [132nd-vWing/Website#24]
<img width="971" alt="image" src="https://user-images.githubusercontent.com/18462495/92324661-32dce080-f044-11ea-836a-c376922279ed.png">

Pilot taipan

**Comment by 132nd-FurFace** [comment]
Also a problem for me.  Cannot self qualify on either 108th or 617th TRPs

**Comment by hiSylvan** [comment]
I had mis-paired my curly brackets. If I had a € for every time I did that I'd be a millionaire by now...
